### ISSUE TITLE
New order emails not sending and transactionstatus processing stuck at "running" (probably related problems)

### ISSUE THREAD

**Issue by gndk** [PAYONE-GmbH/magento-1#59]
I'm running Magento 1.9.3.2 with the latest master commit.

After launching this new store and a few orders came in I noticed that new order emails are not getting sent. I am using Aschroder's MageSend extension to send through Amazon SES. New user account emails are sent. New order emails are also sent when using the "send order email" link in the order overview in admin.

First I thought that MageSend is the problem, but as other email is sending properly and MageSend is properly extending core functions which you use to send email I can rule this out.

I then saw a closed issue (#41) here about that exact extension and emails not sending. In this issue @fjbender mentioned that the transactionstatus could be a problem. So I looked into that and found out that the exact time when the order email is sent is when the transactionstatus is set to appointed.

So I verified that the Magento cron is running properly (it is) and transactionstatus' are processed. They are, but are stuck on "running". I guess this is the reason why the order emails are never sent out. 

I tried resetting them by setting status to "pending" in the db table. A few min later I checked again and everything was back stuck to "running". The exception are some test orders that I deleted. These are set to "error" with the error message "Reference: xxxxx". So the payone transactionstatus cron is properly running. It just doesnt go from "running" to "complete".

The weird thing is, that the order status mapping works properly. So orders are mapped to "payment pending" on "appointed" and to "processing" on "paid".

But the transactionstatus is stuck at "running" and new order emails (or invoice emails on "paid") are not sent.

Also, when I go to PAYONE -> Logs -> Transaction Status in Admin and View one of them, then click "Go to transaction" in the top right, I get a 404 error for url /index.php/admin/admin/adminhtml_transaction/view/id/48/key/xxxxxx.

But when I go to to PAYONE -> Transactions and view the same transaction with id 48, I see it just like normal, but with URL /index.php/admin/admin/payonecore_transaction/view/id/48/key/xxxxx (payonecore_transaction instead of adminhtml_transaction).

Possible related?

Any idea what I could do about this?

**Comment by T-Kuchel** [comment]
Hi gndk,

first of all, thnal you for this detailed descrition. I think you are running into several problem but the base problem is that the transaction status could not proccessed correctly. Missing / deleted orders that could not be mapped are causing that.
The emails only will be sent out when the transaction status is proccessed.

The second issue with the 404 on the API-Log maybe based on two problems. First there could be a relation to the missing orders you deleted and next there maybe installing / update problems. Everytime when such a problem appears, fragments of "old" data or files are causing this.
I.e. in our testenvironment we delete all files relating the extension before update to avoid this.

I hope this hints will help.

**Comment by gndk** [comment]
Hi, 

thanks for the quick response. After backing up I deleted the entries relating to the deleted orders from payone_protocol_transactionstatus and set all remaining (which are all existing orders) to pending. Unfortunately still stuck at "running". I also noticed that the payone transactionstatus cronjob is also stuck at "running" in cron_schedule.

I checked the system.log and now found an error:

2017-03-27T07:28:04+00:00 ERR (3): Notice: unserialize(): Error at offset 665 of 670 bytes  in /home/cloudpanel/htdocs/www.mysite.com/releases/2017_03_26_15_32_44_branch_dev/app/code/community/Payone/Core/Model/Domain/Protocol/TransactionStatus.php on line 314

Line 314 is $aRaw = unserialize($this->_data['raw_request']);

of the function:

public function getRawRequestArray() 
    {
        if(!empty($this->_data['raw_request'])) {
            $aRaw = unserialize($this->_data['raw_request']);
            if($aRaw) {
                return $aRaw;
            }
        }

        return false;
    }

Any idea?

**Comment by gndk** [comment]
It seems like the raw request is incomplete, heres an example:

a:35:{s:3:"key";s:32:"d2884436c42f748b03511d00c6c15558";s:8:"txaction";s:9:"appointed";s:8:"portalid";s:7:"2020136";s:3:"aid";s:5:"36408";s:12:"clearingtype";s:3:"wlt";s:14:"notify_version";s:3:"7.4";s:6:"txtime";s:10:"1490451354";s:8:"currency";s:3:"EUR";s:6:"userid";s:8:"98688065";s:10:"accessname";s:0:"";s:10:"accesscode";s:0:"";s:5:"param";s:0:"";s:4:"mode";s:4:"live";s:5:"price";s:5:"12.99";s:4:"txid";s:9:"219608103";s:9:"reference";s:10:"2100000059";s:14:"sequencenumber";s:1:"1";s:7:"company";s:20:"Gandke Ventures GmbH";s:9:"firstname";s:9:"Alexander";s:8:"lastname";s:6:"Gandke";s:6:"street";s:17:"Stresemannstr. 26";s:3:"zip";s:5:"41236";s:4:"city";s:15:"M

It ends abruptly..

**Comment by gndk** [comment]
It seems like the raw request is incomplete, heres an example:

a:35:{s:3:"key";s:32:"d2884436c42f748b03511d00c6c15558";s:8:"txaction";s:9:"appointed";s:8:"portalid";s:7:"2020136";s:3:"aid";s:5:"36408";s:12:"clearingtype";s:3:"wlt";s:14:"notify_version";s:3:"7.4";s:6:"txtime";s:10:"1490451354";s:8:"currency";s:3:"EUR";s:6:"userid";s:8:"98688065";s:10:"accessname";s:0:"";s:10:"accesscode";s:0:"";s:5:"param";s:0:"";s:4:"mode";s:4:"live";s:5:"price";s:5:"12.99";s:4:"txid";s:9:"219608103";s:9:"reference";s:10:"2100000059";s:14:"sequencenumber";s:1:"1";s:7:"company";s:20:"Test Ventures GmbH";s:9:"firstname";s:9:"gndk";s:8:"lastname";s:6:"Test";s:6:"street";s:17:"Teststr. 26";s:3:"zip";s:5:"41236";s:4:"city";s:15:"M

It ends abruptly..

**Comment by gndk** [comment]
I looked at more raw requests. They always break once there is an Umlaut like ö,ä,ü etc in the fields. In the case above the city was "Mönchengladbach" and it stopped at the ö.

For order with not special letters the raw request is complete.

**Comment by T-Kuchel** [comment]
Yes. I have the same result here regarding your example. I have looked in out testenviroment and i can reproduce this issue.
We will take care of this.

**Comment by gndk** [comment]
Unforunately seems like this isnt the solution to the transactionstatus processing problem..

I set all processing_status's to complete and only set the ones with complete raw request to pending to rule out this error. Unfortunately still stuck at "running".. 

Any way to debug/log where exactly they are getting stuck?

**Comment by nige-one** [comment]
Same here... Magento 1.9.3.1, Payone 3.7.5

**Comment by gndk** [comment]
Hi,

any idea how to debug whats going wrong with the transactionstatus processing?

Another detail this morning:

I received a bank transfer payment this morning. This was recognized by Payone through the automatic bank account reconciliation. For this payment I received the "paid" transactionstatus and a invoice was generated and invoice email sent automatically, like I am used to from my other shop. However for example for other orders that are paid directly, for example via Paypal, nothing happens when I receive the "paid" transationstatus..

**Comment by FatchipRobert** [comment]
The incomplete raw request and the 404 API-Log errors are fixed.

I can't reproduce the "stuck in status running" problem unfortunately.
Would it maybe be possible for you to find out which line makes the cronjob stop working?

The processing_status of the transactionstatus is set to running in the following file:
app/code/community/Payone/Core/Model/Service/TransactionStatus/Execute.php ( line 92 )

The main handling of the transactionstatus is then happening in
app/code/community/Payone/Core/Model/Service/TransactionStatus/Process.php ( starting from line 66 )

**Comment by gndk** [comment]
I'll try, however I'm really not that familiar with magento code.

Would it be possible for you to look at this directly on my site? You can invoice me for it of course.

**Comment by gndk** [comment]
More problems overnight, without changing/touching anything:

1) Transactionstatus is now at least 2-3 hours delayed. For example order played and paid via Paypal at 7:11am. Shows up in transactionstatus log at 9:30am.

2) Order ID field in the transactionstatus "general parameter" section is now empty

3) Order status mapping doesnt work anymore (probably because the order id is empty)

**Comment by nige-one** [comment]
Can you confirm that the patch by FatchipRobert solves your particular issue of this thread?
(Please do not sum up your issues in one thread if they are not obviously linked to each other.)

**Comment by gndk** [comment]
Where else should I sum it up? It all revolves around the transactionstatus processing issue.

What I did now is:
- Removed all Payone files
- Installed development branch commit c6d92aa with the changes by FatchipRobert

This solves the 404 in API log and the incomplete raw requests. Those now are complete in the db.

It does not solve the transactionstatus stuck at running, or the recently gone missing data in the transactionstatus view.

While checking how the raw requests are saved in payone_protocol_transactionstatus I noticed that suddenly the store_id and order_id fields are null, starting late yesterday evening, without any change to any payone files.

I also noticed that the mid (I guess merchant id?) field is null for ALL transactionstatus. My guess is this leads to the processing being stuck.. Merchant ID is saved correctly in the configuration.

See here https://screencast.com/t/jxQu4Tzov

Could the problem be connected to the transactionstatus URL set in PMI? I am using different store views attached to base url, so domain.com/de, /en, etc. For this reason I had to the transactionstatus URL in PMI to /de/payone_core/transactionStatus instead of the standard /index.php/payone_core/transactionStatus or the store would not receive it.

**Comment by FatchipRobert** [comment]
It is normal that the mid field is null, this should have nothing to do with the problem.

The store_id and order_id fields are null too at the beginning, those fields are filled during the cronjob is running. So nothing unusual there.

**Comment by gndk** [comment]
Ok. Can I pay you to help me with this? I dont know how to proceed.

**Comment by FatchipRobert** [comment]
I added a logging mode for the TransactionStatus cronjob execution.
This needs to be activated in the PAYONE misc config in the admin config.
When activated it will write log messages to the /var/log/payone_cron.log file.

A clean execution of a TransactionStatus would look like this:
2017-03-29T12:13:31+00:00 INFO (6): Started cronjob
2017-03-29T12:13:31+00:00 INFO (6): ID: 103 - Execute - Execute TransactionStatus action: appointed - store-id: 
2017-03-29T12:13:31+00:00 INFO (6): ID: 103 - Execute - Set status to running
2017-03-29T12:13:31+00:00 INFO (6): ID: 103 - Process - Got order id: 245 store-id: 1
2017-03-29T12:13:31+00:00 INFO (6): ID: 103 - Process - Update TransactionStatus
2017-03-29T12:13:31+00:00 INFO (6): ID: 103 - Process - Update order status
2017-03-29T12:13:31+00:00 INFO (6): ID: 103 - Process - Add order comment
2017-03-29T12:13:31+00:00 INFO (6): ID: 103 - Process - Store clearing parameters
2017-03-29T12:13:31+00:00 INFO (6): ID: 103 - Process - Save before events
2017-03-29T12:13:31+00:00 INFO (6): ID: 103 - Process - Trigger event payone_core_transactionstatus_all
2017-03-29T12:13:31+00:00 INFO (6): ID: 103 - Process - Trigger event payone_core_transactionstatus_appointed
2017-03-29T12:13:31+00:00 INFO (6): ID: 103 - Process - Finished
2017-03-29T12:13:31+00:00 INFO (6): ID: 103 - Execute - Finished service execution, set status to complete
2017-03-29T12:13:31+00:00 INFO (6): ID: 103 - Execute - Finished
2017-03-29T12:13:31+00:00 INFO (6): executePending: finished 1
2017-03-29T12:13:31+00:00 INFO (6): Finished cronjob

I'd guess that your cronjob execution stops somewhere in the middle, please post one of your reports for further investigation.

**Comment by gndk** [comment]
I added more log messages for smaller steps..

2017-03-29T13:24:01+00:00 INFO (6): Started cronjob
2017-03-29T13:24:01+00:00 INFO (6): ID: 34 - Execute - Execute TransactionStatus action: paid - store-id: 1
2017-03-29T13:24:01+00:00 INFO (6): ID: 34 - Execute - Set status to running
2017-03-29T13:24:01+00:00 INFO (6): ID: 34 - Process - Got order id: 65 store-id: 1
2017-03-29T13:24:01+00:00 INFO (6): ID: 34 - Process - Update TransactionStatus
2017-03-29T13:24:01+00:00 INFO (6): ID: 34 - Process - Update order status
2017-03-29T13:24:01+00:00 INFO (6): ID: 34 - Process - Add order comment
2017-03-29T13:24:01+00:00 INFO (6): ID: 34 - Process - Store clearing parameters
2017-03-29T13:24:01+00:00 INFO (6): ID: 34 - Process - Save before events
2017-03-29T13:24:01+00:00 INFO (6): ID: 34 - Process - getModelResourceTransaction()
2017-03-29T13:24:01+00:00 INFO (6): ID: 34 - Process - addObject(order)
2017-03-29T13:24:01+00:00 INFO (6): ID: 34 - Process - addObject(transactionStatus)

It stops at $resouce->save();

**Comment by FatchipRobert** [comment]
Can you find any sort of exception-log or php error-log on your server with any further information?
The script shouldnt just stop without saying anything.

**Comment by gndk** [comment]
I checked Magento's system.log and exception.log, also /reports folder. Nothing there regarding anything from payone.

Also nothing in nginx error.log and php error.log.. :/

**Comment by gndk** [comment]
I checked again now found sth in magento exception.log

2017-03-28T22:03:51+00:00 ERR (3): 
Payone_Core_Exception_OrderNotFound in /home/cloudpanel/htdocs/www.domain.com/releases/2017_03_28_23_59_45_branch_dev/app/code/community/Payone/Core/controllers/TransactionStatusController.php:63
Stack trace:
#0 /home/cloudpanel/htdocs/www.domain.com/releases/2017_03_28_23_59_45_branch_dev/app/code/local/Mage/Core/Controller/Varien/Action.php(417): Payone_Core_TransactionStatusController->indexAction()
#1 /home/cloudpanel/htdocs/www.domain.com/releases/2017_03_28_23_59_45_branch_dev/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#2 /home/cloudpanel/htdocs/www.domain.com/releases/2017_03_28_23_59_45_branch_dev/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#3 /home/cloudpanel/htdocs/www.domain.com/releases/2017_03_28_23_59_45_branch_dev/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#4 /home/cloudpanel/htdocs/www.domain.com/releases/2017_03_28_23_59_45_branch_dev/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#5 /home/cloudpanel/htdocs/www.domain.com/releases/2017_03_28_23_59_45_branch_dev/index.php(91): Mage::run('', 'store')
#6 {main}

Thats roughly the point since when no order id and store id are saved and status mapping doesnt work anymore. Although I didnt delete any orders. Unfortunately doesnt mention the missing order id. Will try to find it..

**Comment by FatchipRobert** [comment]
Thats another spot in the process though.
Thats the script thats receives the TransactionStatus from PAYONE and writes it into the DB.
The cronjob would be the following step.

The problem of order id, store id and status not being updated anymore can be explained by the moment of the cronjob dying. They are not being updated, because the order- and the transaction-status object cant be saved for whatever reason there.

But this still worked before? Was the only change that you switched to my changes from the developement branch?

**Comment by gndk** [comment]
I did the switch to your changes / the development branch this morning around 11.

The first order_id  and store_id that are NULL in the db table are from yesterday evening. The created at timestamp for the first transactionstatus with order_id null is 2017-03-28 23:05:40 in the db table and shows as 	29.03.2017 01:05:40 in the transactionstatus log in Magento.

So it might be related to the exception since its 22:03 for the exception and 23:05 for the status without order. The timezones seem to be completely messed up.

However the order for the first transactionstatus with order id = NULL definitely exists, I checked it with the reference_id in the status table.

Yes, thats the only change. I didnt make any changes to the payone files yesterday evening around the time it stopped saving the order id.

What I did though was manually processing the orders so customers dont wonder was going on with their order. I manually sent out the order confirmation emails and manually created the invoices for orders with transactionstatus PAID. Could that be a problem?

**Comment by gndk** [comment]
I just noticed something new.

I set all existing transactionstatuses to complete in the db table, to rule out errors from the incomplete raw requests from older orders etc.

Now the cron log for new orders looks different:

2017-03-29T18:08:01+00:00 INFO (6): ID: 345 - Execute - Execute TransactionStatus action: appointed - store-id: 
2017-03-29T18:08:01+00:00 INFO (6): ID: 345 - Execute - Set status to running
2017-03-29T18:08:01+00:00 INFO (6): ID: 345 - Process - Got order id: 301 store-id: 1
2017-03-29T18:08:01+00:00 INFO (6): ID: 345 - Process - Update TransactionStatus
2017-03-29T18:08:01+00:00 INFO (6): ID: 345 - Process - Update order status
2017-03-29T18:08:01+00:00 INFO (6): ID: 345 - Process - Add order comment
2017-03-29T18:08:01+00:00 INFO (6): ID: 345 - Process - Store clearing parameters
2017-03-29T18:08:01+00:00 INFO (6): ID: 345 - Process - Save before events
2017-03-29T18:08:01+00:00 INFO (6): ID: 345 - Process - getModelResourceTransaction()
2017-03-29T18:08:01+00:00 INFO (6): ID: 345 - Process - addObject(order)
2017-03-29T18:08:01+00:00 INFO (6): ID: 345 - Process - addObject(transactionStatus)
2017-03-29T18:10:01+00:00 INFO (6): Started cronjob
2017-03-29T18:10:01+00:00 INFO (6): ID: 346 - Execute - Execute TransactionStatus action: paid - store-id: 
2017-03-29T18:10:01+00:00 INFO (6): ID: 346 - Execute - Set status to running
2017-03-29T18:10:01+00:00 INFO (6): ID: 346 - Process - Got order id: 299 store-id: 1
2017-03-29T18:10:01+00:00 INFO (6): ID: 346 - Process - Update TransactionStatus
2017-03-29T18:10:01+00:00 INFO (6): ID: 346 - Process - Update order status
2017-03-29T18:10:01+00:00 INFO (6): ID: 346 - Process - Add order comment
2017-03-29T18:10:01+00:00 INFO (6): ID: 346 - Process - Store clearing parameters
2017-03-29T18:10:01+00:00 INFO (6): ID: 346 - Process - Save before events
2017-03-29T18:10:01+00:00 INFO (6): ID: 346 - Process - getModelResourceTransaction()
2017-03-29T18:10:01+00:00 INFO (6): ID: 346 - Process - addObject(order)
2017-03-29T18:10:01+00:00 INFO (6): ID: 346 - Process - addObject(transactionStatus)
2017-03-29T18:12:01+00:00 INFO (6): Started cronjob
2017-03-29T18:12:01+00:00 INFO (6): ID: 347 - Execute - Execute TransactionStatus action: paid - store-id: 
2017-03-29T18:12:01+00:00 INFO (6): ID: 347 - Execute - Set status to running
2017-03-29T18:12:01+00:00 INFO (6): ID: 347 - Process - Got order id: 300 store-id: 1
2017-03-29T18:12:01+00:00 INFO (6): ID: 347 - Process - Update TransactionStatus
2017-03-29T18:12:01+00:00 INFO (6): ID: 347 - Process - Update order status
2017-03-29T18:12:01+00:00 INFO (6): ID: 347 - Process - Add order comment
2017-03-29T18:12:01+00:00 INFO (6): ID: 347 - Process - Store clearing parameters
2017-03-29T18:12:01+00:00 INFO (6): ID: 347 - Process - Save before events
2017-03-29T18:12:01+00:00 INFO (6): ID: 347 - Process - getModelResourceTransaction()
2017-03-29T18:12:01+00:00 INFO (6): ID: 347 - Process - addObject(order)
2017-03-29T18:12:01+00:00 INFO (6): ID: 347 - Process - addObject(transactionStatus)
2017-03-29T18:14:01+00:00 INFO (6): Started cronjob
2017-03-29T18:14:01+00:00 INFO (6): executePending: finished 0
2017-03-29T18:14:01+00:00 INFO (6): Finished cronjob
2017-03-29T18:15:01+00:00 INFO (6): Started cronjob
2017-03-29T18:15:01+00:00 INFO (6): executePending: finished 0
2017-03-29T18:15:01+00:00 INFO (6): Finished cronjob
2017-03-29T18:16:01+00:00 INFO (6): Started cronjob
2017-03-29T18:16:01+00:00 INFO (6): executePending: finished 0
2017-03-29T18:16:01+00:00 INFO (6): Finished cronjob

The store_id for Execute TransactionStatus is empty.

**Comment by gndk** [comment]
I found sth else in system.log now:

2017-03-30T05:43:01+00:00 ERR (3): User Error: Some transactions have not been committed or rolled back  in /home/cloudpanel/htdocs/www.domain.com/releases/2017_03_30_02_28_47_branch_dev/lib/Varien/Db/Adapter/Pdo/Mysql.php on line 4039
2017-03-30T06:00:01+00:00 ERR (3): User Error: Some transactions have not been committed or rolled back  in /home/cloudpanel/htdocs/www.domain.com/releases/2017_03_30_02_28_47_branch_dev/lib/Varien/Db/Adapter/Pdo/Mysql.php on line 4039
2017-03-30T06:21:01+00:00 ERR (3): User Error: Some transactions have not been committed or rolled back  in /home/cloudpanel/htdocs/www.domain.com/releases/2017_03_30_02_28_47_branch_dev/lib/Varien/Db/Adapter/Pdo/Mysql.php on line 4039

These 3 errors coincide with these 3 cron logs:

2017-03-30T05:43:01+00:00 INFO (6): ID: 397 - Execute - Execute TransactionStatus action: paid - store-id: 
2017-03-30T05:43:01+00:00 INFO (6): ID: 397 - Execute - Set status to running
2017-03-30T05:43:01+00:00 INFO (6): ID: 397 - Process - Got order id: 330 store-id: 1
2017-03-30T05:43:01+00:00 INFO (6): ID: 397 - Process - Update TransactionStatus
2017-03-30T05:43:01+00:00 INFO (6): ID: 397 - Process - Update order status
2017-03-30T05:43:01+00:00 INFO (6): ID: 397 - Process - Add order comment
2017-03-30T05:43:01+00:00 INFO (6): ID: 397 - Process - Store clearing parameters
2017-03-30T05:43:01+00:00 INFO (6): ID: 397 - Process - Save before events
2017-03-30T05:43:01+00:00 INFO (6): ID: 397 - Process - getModelResourceTransaction()
2017-03-30T05:43:01+00:00 INFO (6): ID: 397 - Process - addObject(order)
2017-03-30T05:43:01+00:00 INFO (6): ID: 397 - Process - addObject(transactionStatus)
2017-03-30T06:00:01+00:00 INFO (6): Started cronjob
2017-03-30T06:00:01+00:00 INFO (6): ID: 398 - Execute - Execute TransactionStatus action: appointed - store-id: 
2017-03-30T06:00:01+00:00 INFO (6): ID: 398 - Execute - Set status to running
2017-03-30T06:00:01+00:00 INFO (6): ID: 398 - Process - Got order id: 331 store-id: 1
2017-03-30T06:00:01+00:00 INFO (6): ID: 398 - Process - Update TransactionStatus
2017-03-30T06:00:01+00:00 INFO (6): ID: 398 - Process - Update order status
2017-03-30T06:00:01+00:00 INFO (6): ID: 398 - Process - Add order comment
2017-03-30T06:00:01+00:00 INFO (6): ID: 398 - Process - Store clearing parameters
2017-03-30T06:00:01+00:00 INFO (6): ID: 398 - Process - Save before events
2017-03-30T06:00:01+00:00 INFO (6): ID: 398 - Process - getModelResourceTransaction()
2017-03-30T06:00:01+00:00 INFO (6): ID: 398 - Process - addObject(order)
2017-03-30T06:00:01+00:00 INFO (6): ID: 398 - Process - addObject(transactionStatus)
2017-03-30T06:21:01+00:00 INFO (6): Started cronjob
2017-03-30T06:21:01+00:00 INFO (6): ID: 399 - Execute - Execute TransactionStatus action: appointed - store-id: 
2017-03-30T06:21:01+00:00 INFO (6): ID: 399 - Execute - Set status to running
2017-03-30T06:21:01+00:00 INFO (6): ID: 399 - Process - Got order id: 332 store-id: 1
2017-03-30T06:21:01+00:00 INFO (6): ID: 399 - Process - Update TransactionStatus
2017-03-30T06:21:01+00:00 INFO (6): ID: 399 - Process - Update order status
2017-03-30T06:21:01+00:00 INFO (6): ID: 399 - Process - Add order comment
2017-03-30T06:21:01+00:00 INFO (6): ID: 399 - Process - Store clearing parameters
2017-03-30T06:21:01+00:00 INFO (6): ID: 399 - Process - Save before events
2017-03-30T06:21:01+00:00 INFO (6): ID: 399 - Process - getModelResourceTransaction()
2017-03-30T06:21:01+00:00 INFO (6): ID: 399 - Process - addObject(order)
2017-03-30T06:21:01+00:00 INFO (6): ID: 399 - Process - addObject(transactionStatus)

**Comment by gndk** [comment]
I activated mysql query log for some time. Maybe it helps. I uploaded all log files to https://www.dropbox.com/s/9ycfl4nc0cntpvf/logs.zip?dl=0

**Comment by FatchipRobert** [comment]
I cant find any new information in there.
The mysql log just shows again that the execution stops while the order is being saved and therefore a rollback of the mysql transaction is happening.

**Comment by gndk** [comment]
I finally "solved" this by doing a completely new install.
